# Generated by Django 5.2.17 on 2026-09-26 16:12

import apps.kiln.services.floor_rules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiln', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='softpointprobe',
            name='softPointC',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[apps.kiln.services.floor_rules.validate_soft_point], verbose_name='软化点(℃)'),
        ),
    ]
